### ISSUE TITLE
Upgrade Document For Rule Contribution

### ISSUE THREAD

**Issue by muhammadaa** [abraztsov/ReactSimpleFlexGrid#2]
I think this project is very interesting, but it's good if given the rules in developing it so well ordered development. I see no information how to develop this project well. How about we make a good rule for it. Maybe i will help create a wiki page for it. Do you agree ? :bowtie:

**Comment by abraztsov** [comment]
> how to develop this project well 

Can you show me example of how you want to develop this project ?

**Comment by muhammadaa** [comment]
What I mean is how we describe the changes that took place in this project. So we know the development. Suppose we add a new current style to the grid, the changes can be documented in this repo. What do you think ?

**Comment by abraztsov** [comment]
At the end of ReactSimpleFlexGrid github page you can see **Updates** section. You want to rework it ?

**Comment by muhammadaa** [comment]
Yes, I see. Maybe we can make it more informative and adjust to the version of `ReactNative`.

**Comment by abraztsov** [comment]
Yes, Good idea. If you have an idea how to organized it more informative make pull request and I'll apply changes.
