### ISSUE TITLE
Runtime error caused by PropTypes. Proptypes was remove from React for React 16

### ISSUE THREAD

**Issue by jkornblum** [abraztsov/ReactSimpleFlexGrid#4]
This library causes a run-time error with react 16 or higher.
I think this is because PropTypes was deprecated with 15.5 and removed in 16. 
It is recommended to use [prop-types](https://github.com/facebook/prop-types) now.

Should be a simple fix, I will try to fork and PR.

**Comment by abraztsov** [comment]
Ok, thanks. I'll accept your PR.

**Comment by abraztsov** [comment]
Fixed
