### ISSUE TITLE
Tabbing order on Fields

### ISSUE THREAD

**Issue by delhibabu86** [abraztsov/ReactSimpleFlexGrid#6]
Hi Team
I was looking into your Grid and its awesome. However i do have a query.Right now the field tabbing goes from left to right. However i would like to have them go from top to bottom. Is there a way we can do it with this ReactSimpleFlexGrid. Please guide.

**Comment by tyherox** [comment]
Hey @delhibabu86, 

Not sure if I'm understanding your question correctly but did you perhaps try using the span settings to achieve the top to bottom behavior? If you set the span to 12 (or if you don't want it full-width you could try using offsets) the grid will arrange the components from top to bottom.

**Comment by abraztsov** [comment]
I don't understand what you want to achieve

**Comment by abraztsov** [comment]
No response
