### ISSUE TITLE
Span: 0 not working

### ISSUE THREAD

**Issue by tyherox** [abraztsov/ReactSimpleFlexGrid#7]
It seem like setting span to 0 does not work! Seems like the grid.less file doesn't even have attributes regarding this case =/

**Comment by abraztsov** [comment]
Give me real world example where you need this and I'll add span 0

**Comment by tyherox** [comment]
Hey @abraztsov,

I used to use this for cases where there were entirely different components that needed to be rendered for different screen sizes (devices). For example, I had a client that wanted to build a website that had a certain component with two images for desktop but one image for mobile devices. In such a case, having a span 0 function would be nice to have 👍 

In addition, the document shows that having span set to 0 will have an effect of display: none. If you don't want to implement this that's fine; at least remove it from the docs to avoid confusion? 

Thanks again for the awesome library!!

**Comment by abraztsov** [comment]
Added span 0. Thanks
